language: python

matrix:
  include:
    - python: "3.6"

before_install:
  - sudo rm -f /etc/boto.cfg

cache:
  directories:
    - .pip_download_cache

env:
  global:
    - PIP_DOWNLOAD_CACHE=".pip_download_cache"

before_script:
  - pip install --upgrade pip
  - pip install --upgrade setuptools
  - pip install .[tests]
  - python setup.py develop

script:
  - coverage run -m py.test || exit 1

after_success:
  - coveralls

notifications:
  email:
    - secops@netflix.com
